package com.teacity.entity.model;

import com.teacity.entity.model.base.BaseCode;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "code", primaryKey = "code_id")
public class Code extends BaseCode<Code> {
	
}
