package com.teacity.entity.model;

import com.teacity.entity.model.base.BaseShop;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "shop", primaryKey = "shop_id")
public class Shop extends BaseShop<Shop> {
	
}
