package com.teacity.entity.model;

import com.teacity.entity.model.base.BaseUser;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user", primaryKey = "user_id")
public class User extends BaseUser<User> {
	
}
