package com.teacity.entity.model;

import com.teacity.entity.model.base.BaseUserLogin;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user_login", primaryKey = "user_login_id")
public class UserLogin extends BaseUserLogin<UserLogin> {
	
}
